[package]
name = "derputils"
version = "0.2.0"
authors = [ "MidAutumnMoon <me@418.im>" ]
edition = "2021"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

[dependencies]
anyhow = "1.0.68"
rustix = { version = "0.36.8", features = [ "fs" ] }
