[package]
name = "derputils"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "whereisis"
path = "./bin/whereisis.rs"

[profile.release]
lto = true
codegen-units = 2
panic = "abort"
strip = true

[dependencies]
anyhow = "1.0.68"
